# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = rec {
    unflake_github_denful_den = {
      type = "github";
      owner = "denful";
      repo = "den";
      rev = "7594405b45e0ce2d5a418fe104a26e17f6b1dd8f";
      lastModified = 1790620498;
      narHash = "sha256-20TrStpHRu+QkS0Wn8AmrJd0GiUz8/jiUVvrS9Bm1MU=";
    };
    unflake_github_denful_with-inputs = {
      type = "github";
      owner = "denful";
      repo = "with-inputs";
      rev = "e1df5e3ab5b93eb77a13a981d136c9a389dacb92";
      lastModified = 1790929728;
      narHash = "sha256-SF91ey4hyNLCyNc05VnSvmQA9AvQfGpPlGdXff7DOsM=";
    };
    unflake_github_nix-community_home-manager = {
      type = "github";
      owner = "nix-community";
      repo = "home-manager";
      rev = "833540099ef43cbeb28b1e3f3c21901961edb48e";
      lastModified = 1790928438;
      narHash = "sha256-ZuJbu8VQe/Qzy7GJdZ3Xv7adRllH1o4O7nqONtkhFbA=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "b6c8664de9b6cc07fe5666a29f91884ba81197c4";
      lastModified = 1790652569;
      narHash = "sha256-641r7xrlSOHYoktL9/aArPIYNgZJ9eM5URzSEOtPJDY=";
    };
    unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-zst = {
      type = "tarball";
      url = "https://releases.nixos.org/nixpkgs/nixpkgs-26.11pre1082290.b6c8664de9b6/nixexprs.tar.zst?lastModified=1790652569";
      rev = "b6c8664de9b6cc07fe5666a29f91884ba81197c4";
      lastModified = 1790652569;
      narHash = "sha256-k8Fu4c9Z+4Nh7mUr0cfw++ITQiyEhlWxoJBOkI3tOcQ=";
    };
    unflake_github_denful_with-inputs_flake_false = unflake_github_denful_with-inputs;
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
    unflake_github_denful_den = {
    };
    unflake_github_nix-community_home-manager = {
      nixpkgs = "unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-zst";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
    };
    unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-zst = {
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_github_denful_den = inject "unflake_github_denful_den" "flake.nix" "";
    unflake_github_denful_with-inputs_flake_false = deps.unflake_github_denful_with-inputs_flake_false;
    unflake_github_nix-community_home-manager = inject "unflake_github_nix-community_home-manager" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable" "flake.nix" "";
    unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-zst = inject "unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-zst" "flake.nix" "";
  };
  inputs = {
    den = universe.unflake_github_denful_den;
    home-manager = universe.unflake_github_nix-community_home-manager;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    with-inputs = universe.unflake_github_denful_with-inputs_flake_false;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
